### PR TITLE
merge to master PR

### PR DESCRIPTION
**Pull request by ansaryergesh**

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hi, devs!!  Your test is not running. Please check again to see you can run it locally then request a re-review.

**Comment by ansaryergesh** [comment]
Hi, but for me it is working 
image

**Comment by JamesOkunlade** [comment]
Game is playing when I run `rspec`

image

**Comment by ansaryergesh** [comment]
Ok. I will fix that

**Comment by ansaryergesh** [comment]
Can you check it now? I fixed it

**Review by JamesOkunlade — APPROVED** [review]
Well, it's a 👍 for me. Please go ahead and merge.

Good luck with your future projects.

**Pull request merged**
